qualifications = [
    {'qualification': "BA"},
    {'qualification': "MA"},
    {'qualification': "MBA"},
    {'qualification': "MSC"},
    {'qualification': "MTech"},
    {'qualification': "BSc"},
    {'qualification': "MSc in Computer Science"},
    {'qualification': "MCA"},
    {'qualification': "BBA"},
    {'qualification': "LLB"},
    {'qualification': "LLM"},
    {'qualification': "PhD"},
    {'qualification': "Diploma in Engineering"},
    {'qualification': "Associate Degree"},
    {'qualification': "Certificate in Graphic Design"},
    {'qualification': "Certification in Project Management"},
    {'qualification': "Bachelor of Fine Arts"},
    {'qualification': "Bachelor of Engineering"},
    {'qualification': "Master of Public Health"},
    {'qualification': "Master of Social Work"},
    {'qualification': "Bachelor of Arts in Psychology"},
    {'qualification': "Certificate in Data Science"},
    {'qualification': "Bachelor of Commerce"},
    {'qualification': "Master of Education"},
    {'qualification': "Diploma in Business Administration"},
    {'qualification': "Certificate in Digital Marketing"},
    {'qualification': "Certified Financial Planner"},
    {'qualification': "Certification in Human Resources"},
    {'qualification': "Bachelor of Nursing"},
    {'qualification': "Master of Architecture"},
    {'qualification': "Certified Information Systems Security Professional (CISSP)"},
    {'qualification': "Chartered Financial Analyst (CFA)"},
    {'qualification': "Project Management Professional (PMP)"},
    {'qualification': "Certified Scrum Master (CSM)"},
    {'qualification': "AWS Certified Solutions Architect"},
    {'qualification': "Google Analytics Certification"},
]
