# Generated by Django 5.0.7 on 2024-08-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0002_instructorprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="area",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="pin_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
