# Generated by Django 5.0.7 on 2024-08-08 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0003_alter_useraddress_area_alter_useraddress_pin_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
    ]
