# Generated by Django 5.0.7 on 2024-08-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0004_alter_userprofile_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructorprofile",
            name="address",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("not_specified", "not_specified"),
                ],
                default="not_specified",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Admin", "admin"),
                    ("Instructor", "instructor"),
                    ("Student", "student"),
                    ("Staff", "staff"),
                ],
                default="Admin",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="UserAddress",
        ),
    ]
