# Generated by Django 5.0.7 on 2024-09-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_otpvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpvalidation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
